# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: bash <(curl -s https://codecov.io/bash) -t c6962816-cdf9-44f8-b579-bef240498727
  displayName: 'Run a one-line script'

- script: |
    echo sdf
  displayName: 'Run a multi-line script'
