import './jQuery'
import '~/static/plugins/umeditor/themes/default/css/umeditor.css'
import '~/static/plugins/umeditor/third-party/imgPreview.js'
import '~/static/plugins/umeditor/umeditor.config.js'
import '~/static/plugins/umeditor/umeditor.min.js'
import '~/static/plugins/umeditor/lang/zh-cn/zh-cn.js'
